# Generated by Django 3.2.6 on 2021-09-05 02:56

import audit.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('professor_guide', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city_address', models.CharField(choices=[('Havana', 'Havana'), ('New York', 'New York'), ('Madrid', 'Madrid'), ('London', 'London'), ('Paris', 'Paris')], max_length=50)),
                ('birth_date', models.DateField(verbose_name='birthday date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.group')),
            ],
            bases=(audit.mixins.AuditMixin, models.Model),
        ),
    ]
