# Generated by Django 3.2.6 on 2021-09-11 16:20

import audit.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            bases=(audit.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('female', 'Male'), ('male', 'Female')], max_length=6)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('birth_date', models.DateField(verbose_name='birthday date')),
                ('city_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.city')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.group')),
            ],
            bases=(audit.mixins.AuditMixin, models.Model),
        ),
        migrations.AddField(
            model_name='group',
            name='professor_guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.professor', unique=True),
        ),
    ]
