# Generated by Django 3.2.6 on 2021-09-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='city_address',
            new_name='city',
        ),
    ]
