# Generated by Django 3.2.6 on 2021-09-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StudentGroup',
        ),
    ]
